require("setup.plugin-setup")
require("setup.core.config")
require("setup.core.keymaps") 
require("setup.core.netrw") 
require("setup.plugin.lsp-config")
require("setup.plugin.colorscheme")
require("setup.plugin.MarkdownPreview")
require("setup.plugin.setup-cmp")
